"""adicionando relacionamente material -> supplier

Revision ID: 06502cc545fe
Revises: e4c11d739525
Create Date: 2026-03-29 15:31:02.981505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '06502cc545fe'
down_revision: Union[str, Sequence[str], None] = 'e4c11d739525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.alter_column('materials', 'classification',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.create_foreign_key(None, 'materials', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.alter_column('materials', 'classification',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_column('materials', 'supplier_id')
    # ### end Alembic commands ###
