"""adicionando price_id in budgetservice table

Revision ID: 111cb4d630cd
Revises: 70357ccc9244
Create Date: 2026-05-09 17:35:21.392753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '111cb4d630cd'
down_revision: Union[str, Sequence[str], None] = '70357ccc9244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_services', sa.Column('price_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'budget_services', 'prices', ['price_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budget_services', type_='foreignkey')
    op.drop_column('budget_services', 'price_id')
    # ### end Alembic commands ###
