"""ADICIONANDO SERVICES E SUAS RELAÇÕES...

Revision ID: 1a49e39bdca0
Revises: 6246a3d47279
Create Date: 2026-03-23 20:41:00.209973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a49e39bdca0'
down_revision: Union[str, Sequence[str], None] = '6246a3d47279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('employee_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('material_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services_employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('fixed_expenses', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('impost', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('others_rates', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('profit_margin', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('markup', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services_prices')
    op.drop_table('services_materials')
    op.drop_table('services_employees')
    op.drop_table('services')
    # ### end Alembic commands ###
