"""revisando modelagem

Revision ID: 4a0af7f9e7ca
Revises: e0870ab86f27
Create Date: 2026-06-20 19:52:29.535379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4a0af7f9e7ca'
down_revision: Union[str, Sequence[str], None] = 'e0870ab86f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_services_materials', sa.Column('project_service_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('project_services_materials_ibfk_2'), 'project_services_materials', type_='foreignkey')
    op.create_foreign_key(None, 'project_services_materials', 'project_services', ['project_service_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project_services_materials', 'service_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_services_materials', sa.Column('service_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project_services_materials', type_='foreignkey')
    op.create_foreign_key(op.f('project_services_materials_ibfk_2'), 'project_services_materials', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project_services_materials', 'project_service_id')
    # ### end Alembic commands ###
