"""revisando tabelas de servicos relacionada a materiais e servicos

Revision ID: 518a1554f067
Revises: 
Create Date: 2026-04-23 21:27:23.093832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '518a1554f067'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'material_cost')
    op.drop_column('services', 'employee_cost')
    op.drop_column('services', 'total_cost')
    op.add_column('services_employees', sa.Column('minute_works', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('services_employees', sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('services_materials', sa.Column('qtd_material', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('services_materials', sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services_materials', 'total_cost')
    op.drop_column('services_materials', 'qtd_material')
    op.drop_column('services_employees', 'total_cost')
    op.drop_column('services_employees', 'minute_works')
    op.add_column('services', sa.Column('total_cost', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('services', sa.Column('employee_cost', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('services', sa.Column('material_cost', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###
