"""adicionando customer_id a company

Revision ID: 539b2b11a9ed
Revises: d9dfe378646d
Create Date: 2026-04-10 21:24:17.389285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539b2b11a9ed'
down_revision: Union[str, Sequence[str], None] = 'd9dfe378646d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companys', sa.Column('customer_id', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'companys', ['customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companys', type_='unique')
    op.drop_column('companys', 'customer_id')
    # ### end Alembic commands ###
