"""ADICIONANDO A TABELA DE PRICES...

Revision ID: 62fcf9361f3c
Revises: 99f663360a5b
Create Date: 2026-03-23 20:09:22.973223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fcf9361f3c'
down_revision: Union[str, Sequence[str], None] = '99f663360a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fixed_expenses', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('impost', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('others_rates', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('profit_margin', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('markup', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('employees', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('employees', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'updated_at')
    op.drop_column('employees', 'created_at')
    op.drop_table('prices')
    # ### end Alembic commands ###
