"""adicionando tabela de budgets e budget_services

Revision ID: 70357ccc9244
Revises: 
Create Date: 2026-05-05 22:31:54.215345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70357ccc9244'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('validity_date', sa.Date(), nullable=True),
    sa.Column('date_acceptance', sa.Date(), nullable=True),
    sa.Column('date_starter_services', sa.Date(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('payment_option', sa.Integer(), nullable=False),
    sa.Column('type_discount', sa.String(length=30), nullable=False),
    sa.Column('value_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(date_starter_services IS NULL) OR (date_starter_services >= date_acceptance)', name='check_starter_service_after_acceptance'),
    sa.CheckConstraint('(validity_date IS NULL) OR (validity_date >= date_acceptance)', name='check_validity_after_acceptance'),
    sa.CheckConstraint('value_discount >= 0', name='check_budget_value_discount_positive'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companys.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('qtd', sa.Integer(), nullable=False),
    sa.Column('service_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('qtd > 0', name='check_qtd_service_budget_positive'),
    sa.CheckConstraint('service_value > 0', name='check_service_value_budget_positive'),
    sa.CheckConstraint('total_value > 0', name='check_total_value_budget_positive'),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_services')
    op.drop_table('budgets')
    # ### end Alembic commands ###
