"""adicionando coluna de email em companys

Revision ID: 703a99d274ab
Revises: 539b2b11a9ed
Create Date: 2026-04-10 21:32:58.279455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '703a99d274ab'
down_revision: Union[str, Sequence[str], None] = '539b2b11a9ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companys', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'companys', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companys', type_='unique')
    op.drop_column('companys', 'email')
    # ### end Alembic commands ###
