"""REMOVENDO ALGUMAS COLUNAS...

Revision ID: 845bf512992e
Revises: 1a49e39bdca0
Create Date: 2026-03-27 20:46:15.668909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '845bf512992e'
down_revision: Union[str, Sequence[str], None] = '1a49e39bdca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'payment_days')
    op.add_column('services_prices', sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('suppliers', 'receive_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('receive_days', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('services_prices', 'value')
    op.add_column('clients', sa.Column('payment_days', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
