"""adicionando coluna is_delivered

Revision ID: 86c374d13878
Revises: c8a1543a94e5
Create Date: 2026-06-20 19:02:31.794592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c374d13878'
down_revision: Union[str, Sequence[str], None] = 'c8a1543a94e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_services_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_service_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name='check_project_service_material_quantity_positive'),
    sa.CheckConstraint('total_cost >= 0', name='check_project_service_material_total_cost_positive'),
    sa.CheckConstraint('unit_cost >= 0', name='check_project_service_material_unit_cost_positive'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_service_id'], ['project_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('project_services', sa.Column('is_delivered', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_services', 'is_delivered')
    op.drop_table('project_services_materials')
    # ### end Alembic commands ###
