"""ADICIONANDO EMPLOYEES...

Revision ID: 99f663360a5b
Revises: 47b02b19ca62
Create Date: 2026-03-23 19:48:09.004411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99f663360a5b'
down_revision: Union[str, Sequence[str], None] = '47b02b19ca62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
