"""revisando modelagem

Revision ID: b9a9a80c4d0e
Revises: 86c374d13878
Create Date: 2026-06-20 19:32:46.494249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b9a9a80c4d0e'
down_revision: Union[str, Sequence[str], None] = '86c374d13878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_services_materials', sa.Column('service_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('project_services_materials_ibfk_2'), 'project_services_materials', type_='foreignkey')
    op.create_foreign_key(None, 'project_services_materials', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project_services_materials', 'project_service_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_services_materials', sa.Column('project_service_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project_services_materials', type_='foreignkey')
    op.create_foreign_key(op.f('project_services_materials_ibfk_2'), 'project_services_materials', 'project_services', ['project_service_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project_services_materials', 'service_id')
    # ### end Alembic commands ###
