"""criando as tabelas

Revision ID: c4e79929758d
Revises: 
Create Date: 2026-04-02 21:50:08.589775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4e79929758d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contract', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=True),
    sa.Column('money', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hours_per_month', sa.Float(), nullable=False),
    sa.Column('food_assistance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transport_assistance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('others_benefits', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('health_plan', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_per_minute', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('employee_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('material_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services_employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('fixed_expenses', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('impost', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('others_rates', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('profit_margin', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('markup', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('clients', 'payment_days')
    op.add_column('materials', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.alter_column('materials', 'classification',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.create_foreign_key(None, 'materials', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    op.add_column('prices', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('prices', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('suppliers', 'receive_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('receive_days', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('prices', 'updated_at')
    op.drop_column('prices', 'created_at')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.alter_column('materials', 'classification',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_column('materials', 'supplier_id')
    op.add_column('clients', sa.Column('payment_days', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('services_prices')
    op.drop_table('services_materials')
    op.drop_table('services_employees')
    op.drop_table('services')
    op.drop_table('employees')
    op.drop_table('segments')
    # ### end Alembic commands ###
