"""deixando status_id em projects  como nullable

Revision ID: c8a1543a94e5
Revises: 1bfe94b9a11d
Create Date: 2026-06-06 17:18:09.355229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c8a1543a94e5'
down_revision: Union[str, Sequence[str], None] = '1bfe94b9a11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'status_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('projects_ibfk_4'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'status_projects', ['status_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_ibfk_4'), 'projects', 'status_projects', ['status_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('projects', 'status_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
