"""revisando modelagem

Revision ID: d0b43f98813b
Revises: a8f5da44b213
Create Date: 2026-06-20 19:48:37.735927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b43f98813b'
down_revision: Union[str, Sequence[str], None] = 'a8f5da44b213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_services_materials', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'project_services_materials', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_services_materials', type_='foreignkey')
    op.drop_column('project_services_materials', 'project_id')
    # ### end Alembic commands ###
