"""adicionando U.K em name da tabela plans

Revision ID: d9dfe378646d
Revises: c4e79929758d
Create Date: 2026-04-04 14:03:09.941050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9dfe378646d'
down_revision: Union[str, Sequence[str], None] = 'c4e79929758d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'plans', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plans', type_='unique')
    # ### end Alembic commands ###
