"""revisando modelagem

Revision ID: e0870ab86f27
Revises: d0b43f98813b
Create Date: 2026-06-20 19:50:44.471821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e0870ab86f27'
down_revision: Union[str, Sequence[str], None] = 'd0b43f98813b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('project_services_materials_ibfk_3'), 'project_services_materials', type_='foreignkey')
    op.drop_column('project_services_materials', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_services_materials', sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('project_services_materials_ibfk_3'), 'project_services_materials', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
