"""alterando nome de payment_form para payment_condition

Revision ID: f7a8750202ba
Revises: db84c061520a
Create Date: 2026-05-23 16:30:38.987403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f7a8750202ba'
down_revision: Union[str, Sequence[str], None] = 'db84c061520a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('payment_condition', sa.Integer(), nullable=False))
    op.drop_column('budgets', 'payment_option')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('payment_option', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('budgets', 'payment_condition')
    # ### end Alembic commands ###
